spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package:

logging:
  level:
    jdbc:
      sqlony : off
      sqltiming : info
      resultsettable : info
      audit: off
      resultset : off
      connection: off

